language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  # - ng lint
  - ng build --aot --prod --base-href https://shmy.github.io/free-immi-web/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/free-immi-web
  on:
    branch: master
